### ISSUE TITLE
Use -u instead of --utc for the 'date' command

### ISSUE THREAD

**Issue by mavilov** [didier-durand/lambda-cobol#1]
Hi Didier,

I would suggest -u over --utc here as it is more portable. With -u it will work on Mac OS as well.
https://github.com/didier-durand/lambda-cobol/blob/bbe0a1522b81092632889906ff0688e7a3256260/lambda-cobol.sh#L8

**Comment by didier-durand** [comment]
@mavilov : Maksim, I didn't know that. Thanks! Fixed with commit mentioned above. Closing.
