### ISSUE TITLE
GnuCOBOL spelling error

### ISSUE THREAD

**Issue by GitMensch** [didier-durand/lambda-cobol#2]
Some people moved COBOL from an acronym to just another name of a programming language like Java.
You are of course free to do this (although I find that spelling mostly in places where people don't know much of the language, which doesn't seem to be the case here), but you may consider adjusting it.

In any case: GnuCOBOL is the definitely correct spelling, so please adjust that.

Notes:
You may want to use the "direct" page for official releases, that would be https://ftp.gnu.org/gnu/gnucobol/?C=M;O=D. 

In in case you want to use an icon for your slides (not important, but I've recognized that at least those on the AWS blog have one for everything but for GnuCOBOL), you'd find it [here](https://gnucobol.sourceforge.io/shire_200.png) (png, 200px) or the [hi-res version](https://gnucobol.sourceforge.io/files/Shire.svg) (svg 3,3MB, default rendered with ~1200px).

**Comment by didier-durand** [comment]
@GitMensch : thanks for your input. It has been applied to the README. Closing this ticket.
